# Generated by Django 6.0.1 on 2026-01-07 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ('id',)},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['user', '-created_at'], name='quiz_manage_user_id_33efa4_idx'),
        ),
    ]
